"""add post_tag table

Revision ID: 811ee8bd11b5
Revises: 0a27ca602dc3
Create Date: 2023-08-03 00:00:03.692692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811ee8bd11b5'
down_revision = '0a27ca602dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
    sa.Column('postId', sa.Integer(), nullable=True),
    sa.Column('tagId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postId'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tagId'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tag')
    # ### end Alembic commands ###
